Change layout
hackclub/hackathons-v1 pull request #26
Opened 2018-05-31 07:50 UTC by yevbar

The site now has two sections where the top section holds events that have not occurred whereas the bottom second holds events that have already occurred

2018-05-31 18:58 UTC, maxwofford requested changes

2018-05-31 18:58 UTC, MaxWofford commented on src/pages/index.js
> +      timeFilter: 'bazinga',
What does this do? It looks like you already removed all uses of `this.state.timeFilter`

2018-05-31 18:58 UTC, MaxWofford commented on src/pages/index.js
> +              Events that are coming right up&#33;
Is there a reason we're using `&#33;` here?

2018-05-31 18:58 UTC, MaxWofford commented on src/pages/index.js
> +                Events that have already passed&#33;
`&#33;`

2018-05-31 18:58 UTC, MaxWofford commented on src/pages/index.js
> +                Events that have already passed&#33;
I think this could actually just drop the exclamation & be fine

2018-05-31 18:58 UTC, MaxWofford commented on src/pages/index.js
> +            <Flex mx={[1, 2, -3]} wrap justify="center">
Now that there are 2 of these on the page, want to make something like an `EventsList` component?

2018-06-01 00:25 UTC, yevbar commented on src/pages/index.js
> +      timeFilter: 'bazinga',
That was put in as a placeholder filter

2018-06-01 00:25 UTC, yevbar commented on src/pages/index.js
> +              Events that are coming right up&#33;
My editor complained about the exclamation mark, changing

2018-06-01 00:27 UTC, yevbar commented on src/pages/index.js
> +                Events that have already passed&#33;
Alright, leaving exclamation mark out

2018-06-01 00:43 UTC, closed without merging

2018-06-01 00:43 UTC, yevbar commented
The git inserts and notes got in :\

2018-06-02 03:24 UTC, lachlanjc commented
I'd like to implement these changes. Can you move the good commits to a new branch and PR? Thanks :)