Fix email list signup
hackclub/hackathons-v1 pull request #28
Opened 2018-06-05 23:28 UTC by MaxWofford

2018-09-18 02:29 UTC, zanedb requested changes

2018-09-18 02:29 UTC, zanedb commented on src/components/EmailListForm.js
> +const Base = Container.withComponent(form).extend.attrs({
Try to use `styled(Container.withComponent(form)` instead of `.extend`, see: styled-components/styled-components#1546.

2018-09-18 02:31 UTC, lachlanjc commented on src/components/EmailListForm.js
> +const Base = Container.withComponent(form).extend.attrs({
We're going to do a full, mostly-automated migration in the coming week or two of _everything_ to `styled`, then v4 with `as` instead of `withComponent`. For now, I'm just switching to writing `styled` to get in the habit/ease the transition.

2019-01-15 00:55 UTC, zachlatta commented
Can I close this?

2019-01-15 11:01 UTC, lachlanjc commented
I just tried signing up & it works fine, so yeah, closing.

2019-01-15 11:01 UTC, closed without merging

2019-01-15 14:37 UTC, polytroper commented
@lachlanjc wtf are you doing managing the repos at 6am

stop making me look bad with your productivity

> On Jan 15, 2019, at 6:01 AM, Lachlan Campbell <notifications@github.com> wrote:
> 
> Closed #28 <https://github.com/hackclub/hackathons/pull/28>.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/hackclub/hackathons/pull/28#event-2074269065>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AO_gEYSN31F4mg0lNa4ec7obBgr61WgTks5vDbUSgaJpZM4UbwY8>.
>